# Generated by Django 4.2 on 2023-04-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_answers', through='app.Like', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.ManyToManyField(blank=True, related_name='temporary_rating', to='app.profile'),
        ),
    ]
