# Generated by Django 4.2 on 2023-04-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_answer_text_alter_question_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='LikedAnswers',
        ),
        migrations.RenameModel(
            old_name='Rating',
            new_name='LikedQuestions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rate',
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_questions', through='app.LikedQuestions', to='app.profile'),
        ),
    ]
