# Generated by Django 4.2 on 2023-04-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_like_likedanswers_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='likedanswers',
            constraint=models.UniqueConstraint(fields=('answer', 'user_profile'), name='unique_answer_likes'),
        ),
        migrations.AddConstraint(
            model_name='likedquestions',
            constraint=models.UniqueConstraint(fields=('question', 'user_profile'), name='unique_question_likes'),
        ),
    ]
