# Generated by Django 4.2 on 2023-05-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_likedanswers_unique_answer_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='upload/User.png', upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
